[package]
name = "aether-desktop"
version = "0.1.2"
edition = "2021"

[lib]
name = "aether_desktop_lib"
crate-type = ["rlib"]

[[bin]]
name = "aether-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
tauri = { version = "2.12.0", features = ["devtools"] }
tauri-plugin-global-shortcut = "2.4.0"
tauri-plugin-window-state = "2.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
reqwest = { version = "0.13.5", default-features = false, features = [
    "rustls",
    "json",
    "gzip",
    "http2",
    "charset",
    "socks",
    "stream",
    "query",
] }
urlencoding = "2"
rodio = { version = "0.22.2", features = ["symphonia-all"] }
regex = "1.13.1"
futures = "0.3.34"
tokio = { version = "1.53.1", features = ["full"] }
bytes = "1.12.1"
url = "2"
tauri-plugin-dialog = "2.8.0"
zip = "8.6.0"
dirs = "7.0.0"
tauri-plugin-store = { version = "2.5.0" }

[profile.release]
lto = true

[profile.release-fast]
inherits = "release"
codegen-units = 16
lto = "thin"
opt-level = 2
strip = "debuginfo"
incremental = true

[profile.dev.package."*"]
debug = false

[profile.dev]
incremental = false
